markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : LeetCode Solutions
production_url : http://carlosbecker.com
description: "LeetCode Solutions in Java and Python."
disqus_shortname:
analytics:
gauges:
author :
  name : Rio Shen
  github : rioshen
  twitter :
  email:
